### ISSUE TITLE
Errors after last update

### ISSUE THREAD

**Issue by PeteXP956** [welteki/docker_frontail_openhab#2]
First of all, thanks for the container. But after the last update I experience the following errors:
`
Error: Preset file /usr/lib/node_modules/frontail/preset/openhab.json doesn't exists
    at Object.<anonymous> (/usr/local/lib/node_modules/frontail/index.js:116:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/frontail/bin/frontail:2:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    /usr/local/lib/node_modules/frontail/index.js:116
    throw new Error(`Preset file ${presetPath} doesn't exists`);
`

Maybe you can have a look at this.
Thanks a lot!

**Comment by welteki** [comment]
Thanks for reporting this!
I fixed the issue and rebuild the container.

**Comment by PeteXP956** [comment]
Up and working again! Thank you!
